version: "3"

services:
  ngx-angular-time-picker-lib:
    container_name: ngx-angular-time-picker-lib
    image: ngx-angular-time-picker-lib
    restart: always
    network_mode: bridge
    env_file: .env
    ports:
      - "5603:5603"
